DELETE http://localhost:3001/api/blogs/67b305b1fc756d73ae2e9f0c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxvIiwiaWQiOiI2N2IyZjY0MjRmMDFiMmFlOWEyOWNjZDEiLCJpYXQiOjE3Mzk3ODU1MTEsImV4cCI6MTczOTc4OTExMX0.Oq74hl3uOL1_CkLxdLXoKx8j58edXThVbQga1mujc8Y