POST http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxvIiwiaWQiOiI2N2IyZjY0MjRmMDFiMmFlOWEyOWNjZDEiLCJpYXQiOjE3Mzk3ODczNjIsImV4cCI6MTczOTc5MDk2Mn0.ieSVD2er8C5iUtFFMjFljeKc_TznHfEOqIrP8STMdjw

{
  "title": "tester",
  "author": "tester",
  "url": "https:/asas/example.com/",
  "likes": 5
}
