POST http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxvIiwiaWQiOiI2N2IzMGQyNjEzZTAyODE2NDQyYjVhYzUiLCJpYXQiOjE3Mzk4MTQ3NjUsImV4cCI6MTczOTgxODM2NX0.B0Ys0YGTY38G87zboSfwd5J4b1ztyYsKmtrD7WUZqHE
Content-Type: application/json

{
  "title": "tester",
  "author": "tester",
  "url": "https://example.com/tester",
  "likes": 5
}
